/**
 * Standalone helpers for building dynamic file content.
 * Extracted into a separate module to avoid circular dependencies between
 * scaffold.ts (which imports from agents/) and the agent adapters (which
 * need these helpers).
 */
import { getModule } from './modules/registry.js';
import type { TemplateVars } from './types.js';

/**
 * Build the content of the inbox-routing file from all installed modules' declared
 * `inboxRoutes`. Plain table with managed marker — overwritten on every update.
 * The path this file is written to is determined by the caller (agent-specific).
 */
export function buildRoutingFile(modules: readonly string[], vars: TemplateVars): string {
  const routes = modules.flatMap(id => getModule(id)?.inboxRoutes ?? []);
  const rows = routes.length
    ? routes.map(r => {
        const dest = r.destination.endsWith('/') ? r.destination : `${r.destination}/`;
        return `| \`${r.type}\` | \`${vars.CONTENT_DIR}/${dest}\` | ${r.description ?? ''} |`;
      })
    : [`| _(none)_ | — | No modules with routable types are installed. |`];

  const table = [
    '| `type:` value | Destination | Notes |',
    '|---------------|-------------|-------|',
    ...rows,
  ].join('\n');

  const preamble = [
    '---',
    'patina: managed',
    '---',
    '# Inbox routing table',
    '',
    "This file maps the `type:` field in an artifact's frontmatter to the folder it",
    'is filed into when you run `/inbox`. Any `type:` not listed here is **unknown** —',
    `\`/inbox\` will file it to \`${vars.CONTENT_DIR}/notes/\` and surface a visible warning`,
    'naming the type and the nearest registered match.',
    '',
    'The table below is regenerated by patina whenever you add or remove modules.',
    '',
  ].join('\n');

  return preamble + table + '\n';
}

/**
 * Build the body of the update-check section for CLAUDE.md (Claude Code only).
 * The embedded version number is read from `vars.PATINA_VERSION` so it stays
 * accurate on upgrade without any user action.
 */
export function renderUpdateCheckSection(vars: TemplateVars): string {
  return `## Update check

After you finish responding to the user's **first message** of this session — at the natural
end of that response, not mid-task — check for \`.patina-update-check\`.

If the file exists, parse it as JSON:
- It looks like \`{ "checked_at": "<ISO timestamp>", "available_version": "<version or null>" }\`.
- If \`available_version\` is null, missing, or not a valid semver string, say nothing.
- Otherwise, read \`.patina-state.json\`. If \`update_check.last_notified_version\` equals
  \`available_version\`, say nothing (already notified).
- Otherwise, append this notification to the end of your response (fill in the version numbers):

    ---
    There's a newer version of patina available (you have ${vars.PATINA_VERSION}, the latest is [version]).

    To update: finish what you're doing in this session, close this window, and run this
    command in your terminal:

        npx my-patina@latest

    Your notes and settings will stay exactly as they are.
    ---

  - After notifying, write \`available_version\` to \`update_check.last_notified_version\` in
    \`.patina-state.json\`.
- Do NOT delete \`.patina-update-check\`. The checker script re-runs automatically once \`checked_at\` is older than 24 hours.
- If the file is absent or not valid JSON, say nothing.

For version comparison, split on \`.\` and compare major, minor, and patch numerically. If
the value is not a valid semver string, skip silently.

Skip this step entirely in headless or non-interactive sessions.`;
}
